src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>EID__c</fullName>
        <description>Store provider or member id received from OIL. Use it for upserting Accounts used for storing providers and members</description>
        <externalId>true</externalId>
        <inlineHelpText>Text(255) (External ID) (Unique Case Insensitive)</inlineHelpText>
        <label>EID</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Tax_Id__c</fullName>
        <label>Tax ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Caller_Type__c</fullName>
        <formula>TEXT(Interaction__r.Caller_Type__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Caller Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Interaction_Type__c</fullName>
        <formula>TEXT(Interaction__r.Interaction_Type__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Interaction Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Interaction__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Interaction</label>
        <referenceTo>Interaction__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Originator_Type__c</fullName>
        <formula>TEXT(Interaction__r.Originator_Type__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Originator Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TaxID__c</fullName>
        <label>Tax ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Topic__c</fullName>
        <globalPicklist>Topic</globalPicklist>
        <label>Topic</label>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>EID__c</fullName>
        <externalId>true</externalId>
        <label>EID</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>NPI__c</fullName>
        <label>NPI</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Other_Originator__c</fullName>
        <label>Other Originator</label>
        <picklist>
            <picklistValues>
                <fullName>Attorney</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Caregiver</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Collection Agency</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Family/Friend/Spouse</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Insurance Carrier</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Parent/Guardian</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pharmacy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prospective Member</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Provider</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reporter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Representative</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>State Regulatory Agent/Government Agency</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UHG Employee</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Relationship_To_Member__c</fullName>
        <label>Relationship To Member</label>
        <picklist>
            <picklistValues>
                <fullName>Spouse</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Child</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Tax_ID__c</fullName>
        <label>Tax ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Create_Letter__c.object
<CustomObject>
    <fields>
        <fullName>Case__c</fullName>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipName>Create_Letters</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <label>Fulfillment</label>
    <nameField>
        <displayFormat>F-{0000}</displayFormat>
        <label>F-ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fulfillment</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Interaction__c.object
<CustomObject>
    <fields>
        <fullName>Caller_Type__c</fullName>
        <description>This field will have the caller type</description>
        <label>Caller Type</label>
        <picklist>
            <picklistValues>
                <fullName>Benefit Adminstrator/Unlisted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>General Agent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Third Party</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Listed Broker of Record</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Listed General Agent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>President</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vice President</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Director</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chief Executive Officer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chief Operating Officer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chief Financial Officer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Controller</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Assistant Controller</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Member Note</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unlisted Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Owner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UHC Employee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Primary Benefits Administrator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Primary Billing Administrator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Broker</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Contact_Name__c</fullName>
        <label>Contact Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Highlight_Panel_GroupInfo__c</fullName>
        <label>Highlight Panel GroupInfo</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Interaction_Type__c</fullName>
        <label>Interaction Type</label>
        <picklist>
            <picklistValues>
                <fullName>Phone Call</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Email</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chat</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Text</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fax</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Portal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Walk-In</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inbound Correspondence</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Research Only</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Outbound Call</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>NPI__c</fullName>
        <label>NPI</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Originator_Type__c</fullName>
        <label>Originator Type</label>
        <picklist>
            <picklistValues>
                <fullName>Provider</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Member</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Third Party</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Broker</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Group/Employer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>General Agent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UHG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Producer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unlisted Contact</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Originator__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Originator</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Interactions</relationshipLabel>
        <relationshipName>Interactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Tax_Id__c</fullName>
        <label>Provider Tax ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Third_Party__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Third Party</label>
        <referenceTo>Third_Party__c</referenceTo>
        <relationshipLabel>Interactions (Third Party)</relationshipLabel>
        <relationshipName>Interactions1_del</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Interaction</label>
    <nameField>
        <displayFormat>INT-{0}</displayFormat>
        <label>Interaction ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Third_Party__c.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FullName__c</fullName>
        <label>Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NPI__c</fullName>
        <label>NPI</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone_Number__c</fullName>
        <label>Phone Number</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tax_ID__c</fullName>
        <label>Tax ID</label>
        <length>9</length>
        <type>Text</type>
    </fields>
    <label>Third Party</label>
    <nameField>
        <label>Last Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Third Parties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ACETProviderUtility.cls
public without sharing class ACETProviderUtility
{   
 
  public static ACETWSCalloutResult FindAuthorization(String MemberId, String DOB, String FirstName, String LastName, String StartDate, String EndDate,String FederationID, List<String> SystemLabels)
    {
        system.debug(LoggingLevel.INFO, 'MemberId: ' + MemberId + ', DOB: ' + DOB + ', FirstName: ' + FirstName + ', LastName: ' + LastName + ', StartDate: ' + StartDate + ', EndDate: ' + EndDate + ', FederationID: ' + FederationID);    
        ACETFindAuthorizationWebservice ACTFAWS = new ACETFindAuthorizationWebservice();
        ACETWSCalloutResult oACETWSCalloutResult=ACTFAWS.FindAuthorizations(MemberId, DOB, FirstName, LastName,  StartDate,  EndDate, FederationID, SystemLabels);    
        return oACETWSCalloutResult;
    }
    public static ACETWSCalloutResult GetAuthorizationDetail(String AuthId, String XRefId,String Type,String federationID, List<String> SystemLabels)
    {
        system.debug(LoggingLevel.INFO, 'AuthId: ' + AuthId + ', XRefId: ' + XRefId +'Type: ' + Type+'::federationID:: ' + federationID);    
        ACETGetAuthorizationWebservice ACTGAWS = new ACETGetAuthorizationWebservice();
        ACETWSCalloutResult oACETWSCalloutResult=ACTGAWS.GetAuthorizationDetail(AuthId, XRefId,Type,federationID,SystemLabels);    
        return oACETWSCalloutResult;
    }
    
    public static Account CreateProviderAccount(String ProviderId, String ProviderName, String TaxId)
    {
        Account ProviderAccount = new Account();
        ProviderAccount.EID__c = ProviderId;
        ProviderAccount.Name = ProviderName;
        ProviderAccount.Tax_Id__c = TaxId;
        return ProviderAccount;
    }
    
    public static Contact CreateProviderContact(String ProviderType, Account ProviderAccount, String ProviderId, String TaxId, String NPI)
    {
        Contact ProviderContact = new Contact();
        if (ProviderType.equalsIgnoreCase(Label.ACETProviderPhysician))
        {
            String[] Names = ProviderAccount.Name.split(' ');
            ProviderContact.FirstName = Names[0];
            if (Names.size() > 1)
            {
                Integer lenStr = Names.size();               
                ProviderContact.LastName = Names[lenStr-1];
            }
        }
        else
        {
            ProviderContact.FirstName = '';
            ProviderContact.LastName = ProviderAccount.Name;
        }   
        ProviderContact.AccountId = ProviderAccount.Id;
        ProviderContact.EID__c = ProviderId;
        ProviderContact.Tax_Id__c = TaxId;
        ProviderContact.NPI__c = NPI;
        return ProviderContact;
    }
    
    public static Interaction__c CreateInteraction(Id ContactId, String InteractionType, String OriginatorType, String ContactName)
    {
        Interaction__c interaction = new Interaction__c();
        interaction.Originator__c = ContactId; 
        interaction.Interaction_Type__c = InteractionType;
        interaction.Originator_Type__c = OriginatorType;
        interaction.Contact_Name__c = ContactName;
        return interaction;
    }
    
    public static Interaction__c CreateInteraction(String InteractionType, String OriginatorType, String CallerName, String TaxId, String Npi, String LastName, String FirstName, String PhoneNumber)
    {
        Third_Party__c ManualProvider = new Third_Party__c();
        ManualProvider.Tax_ID__c = TaxId;
        ManualProvider.NPI__c = Npi;           
        ManualProvider.Name = LastName;
        ManualProvider.First_Name__c = FirstName;
        ManualProvider.Phone_Number__c = PhoneNumber;
        insert ManualProvider;
        
        Interaction__c interaction = new Interaction__c();
        Interaction.Interaction_Type__c = InteractionType;
        Interaction.Originator_Type__c = OriginatorType;
        Interaction.Contact_Name__c = CallerName; 
        Interaction.Third_party__c = ManualProvider.Id;
        
        return interaction;
    }
    
    public static Interaction__c GetInteractionByID(Id InteractionId)
    {
        Interaction__c Interaction = [SELECT Id, Name, Interaction_Type__c, Originator_Type__c, Caller_Type__c,Highlight_Panel_GroupInfo__c , Contact_Name__c, Originator__c, Originator__r.EID__c, Originator__r.Tax_ID__c, Originator__r.NPI__c, 
            Originator__r.Name, Originator__r.LastName, Originator__r.FirstName, Originator__r.AccountId, Originator__r.Account.Name,Third_party__c, Third_party__r.Tax_ID__c, Third_party__r.NPI__c, 
            Third_party__r.FullName__c, Third_party__r.Name, Third_party__r.First_Name__c, Third_party__r.Phone_Number__c, Third_party__r.Email__c
            FROM Interaction__c WHERE Id =:InteractionId];
        system.debug(JSON.serialize(Interaction));    
        return Interaction;
    }
    
    public static Contact GetContactByID(Id contactId)
    {
        Contact subject = [select id,name,firstname,lastname,eid__c,npi__c,other_originator__c,Account.Name,Relationship_To_Member__c,Tax_ID__c,Birthdate from contact where id =:  contactId];
            
        return subject;    
    }   
     
    public static List<ACETContactHistoryCase> GetACETContactCaseHistory(String TaxId)
    {
        /*List<Case> lstCases = new List<Case>([SELECT Id, CaseNumber, Contact.Name, CreatedBy.Name, CreatedDate, Topic__c, Status, 
                                              Interaction__r.Originator_Type__c, Interaction__r.Interaction_Type__c, Interaction__r.Id, Interaction__r.Name
                                              FROM Case WHERE Tax_ID__c = :TaxId ORDER BY CreatedDate DESC limit 1000]);*/
        
        
        // Rama: Modified above SOQL to SOSL to make the tax ID field compatable for encryption
        List<ACETContactHistoryCase> HistoryCases = new List<ACETContactHistoryCase>();
        
        if(String.isBlank(TaxId) ||  TaxId.length() < 2){
            return HistoryCases;
        }
        List<List <SObject>> searchList = new List<List<SObject>>();
        
        String query = 'FIND  \'' + TaxId + '\' IN ALL Fields Returning Case';
        query += ' (Id, TaxID__c, CaseNumber, Contact.Name, CreatedBy.Name, CreatedDate, Topic__c, Status, Interaction__r.Originator_Type__c, Interaction__r.Interaction_Type__c, Interaction__r.Id, Interaction__r.Name ORDER BY CreatedDate DESC limit 1000)';
        searchList = search.query(query);
        
        Set<String> setCaseId = new Set<String>();
        Map<String,Integer> mapCaseIdtoChildRecordsCount = new Map<String,Integer>();
        for(Case oCase : (List<Case>)searchList[0]){
             
            setCaseId.add(oCase.Id); 
        }
        
        for(AggregateResult objAgg: [SELECT Count(Id) cnt,Case__c FROM Create_Letter__c WHERE Case__c =: setCaseId Group by Case__c]){
            
            mapCaseIdtoChildRecordsCount.put(String.valueOf(objAgg.get('Case__c')),Integer.valueOf(objAgg.get('cnt')));
        }
        
        ACETContactHistoryCase HistoryCase;
        for(Case oCase : (List<Case>)searchList[0]){
            if(oCase.TaxID__c == TaxId){
                HistoryCase = new ACETContactHistoryCase();    
                HistoryCase.SFDCId = oCase.Id;
                HistoryCase.CaseNumber = oCase.CaseNumber;
                HistoryCase.SubjectName = String.isBlank(oCase.Contact.Name) ? '' : oCase.Contact.Name;
                HistoryCase.CreatedBy = oCase.CreatedBy.Name;
                HistoryCase.CreatedDate = oCase.CreatedDate;
                HistoryCase.CallTopic = String.isBlank(oCase.Topic__c) ? '' : oCase.Topic__c;
                HistoryCase.Status = String.isBlank(oCase.Status) ? '' : oCase.Status;
                HistoryCase.OriginatorType = oCase.Interaction__r.Originator_Type__c;
                HistoryCase.InteractionType = oCase.Interaction__r.Interaction_Type__c;
                HistoryCase.InteractionSFDCId = oCase.Interaction__r.Id;
                HistoryCase.InteractionName = oCase.Interaction__r.Name;
                HistoryCase.FullfillmentSize = (mapCaseIdtoChildRecordsCount.containsKey(oCase.Id))?mapCaseIdtoChildRecordsCount.get(oCase.Id):0;
                HistoryCases.add(HistoryCase);
            }
        }
        
        return HistoryCases;
    }
    
    //Code Snippet to get the Custom Metadata Types added by Avish 05192017
    public Map<String, Provider_Taxonomy__mdt> getProviderTaxonomy(){
        Map<String, Provider_Taxonomy__mdt> mapTaxonomy = new Map<String, Provider_Taxonomy__mdt>();
        List<Provider_Taxonomy__mdt> provTaxonomyLst = [select Classification__c,Provider_Type__c,Speciality__c,Speciality_Code__c from Provider_Taxonomy__mdt];
        for(Provider_Taxonomy__mdt pt : provTaxonomyLst){
          //  if(!mapTaxonomy.containsKey(pt.Speciality_Code__c)){
                mapTaxonomy.put(pt.Speciality_Code__c, pt);
          //  }
        }           
                
        return mapTaxonomy;
    } 
    
    //Added By Avish to get the federaionID value to map while making web service callout on 06052017
    public static String getFederationIDByUserID(){
        User usr = [Select Id, FederationIdentifier from User where Id=:userinfo.getuserId()];
        return usr.FederationIdentifier;
    }

    //Added By Avish to concatenate fields on View Authorization page on 06122017
    public static String validateConcatenateOfStrings(String firstString, String secondString, String symbolToAppend){
        String resultStr = '';
        if(String.isNotBlank(firstString) && String.isNotBlank(secondString)){
            resultStr = firstString + ' ' + symbolToAppend + ' ' + secondString;
        }else if(String.isNotBlank(firstString) && String.isBlank(secondString)){
            resultStr = firstString + ' ' + symbolToAppend;
        }else if(String.isNotBlank(secondString) && String.isBlank(firstString)){
            resultStr = symbolToAppend + ' ' + secondString;
        }
        
        return resultStr;
    }        
       
}