src/objects/Alert__c.object
<CustomObject>
    <description>Used to store Provider and Member Alerts which are imported into SF from UHG SharePoint</description>
    <fields>
        <fullName>ID_Number__c</fullName>
        <description>Based on alert type, either member&apos;s id or provider&apos;s tax id</description>
        <label>ID Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Alert</label>
    <nameField>
        <displayFormat>A-{000000000}</displayFormat>
        <label>Alert ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Alerts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Caller_Type__c</fullName>
        <formula>TEXT(Interaction__r.Caller_Type__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Caller Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Interaction_Type__c</fullName>
        <formula>TEXT(Interaction__r.Interaction_Type__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Interaction Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Interaction__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Interaction</label>
        <referenceTo>Interaction__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Originator_Type__c</fullName>
        <formula>TEXT(Interaction__r.Originator_Type__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Originator Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Rollup_Fulfillment__c</fullName>
        <description>Rollup of fulfillment (letter)</description>
        <label>Rollup : Fulfillment</label>
        <summaryForeignKey>Create_Letter__c.Case__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Topic__c</fullName>
        <globalPicklist>Topic</globalPicklist>
        <label>Topic</label>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>EID__c</fullName>
        <externalId>true</externalId>
        <label>EID</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Tax_ID__c</fullName>
        <label>Tax ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Create_Letter__c.object
<CustomObject>
    <fields>
        <fullName>Case__c</fullName>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipName>Create_Letters</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Fulfillment</label>
    <nameField>
        <displayFormat>F-{0000}</displayFormat>
        <label>F-ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fulfillment</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Interaction__c.object
<CustomObject>
    <fields>
        <fullName>Caller_Type__c</fullName>
        <description>This field will have the caller type</description>
        <label>Caller Type</label>
        <picklist>
            <picklistValues>
                <fullName>Benefit Adminstrator/Unlisted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>General Agent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Third Party</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Listed Broker of Record</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Listed General Agent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>President</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vice President</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Director</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chief Executive Officer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chief Operating Officer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chief Financial Officer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Controller</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Assistant Controller</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Member Note</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unlisted Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Owner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UHC Employee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Primary Benefits Administrator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Primary Billing Administrator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Broker</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Contact_Name__c</fullName>
        <label>Contact Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Interaction_Type__c</fullName>
        <label>Interaction Type</label>
        <picklist>
            <picklistValues>
                <fullName>Phone Call</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Email</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chat</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Text</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fax</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Portal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Walk-In</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inbound Correspondence</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Research Only</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Outbound Call</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Originator_Type__c</fullName>
        <label>Originator Type</label>
        <picklist>
            <picklistValues>
                <fullName>Provider</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Member</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Third Party</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Broker</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Group/Employer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>General Agent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UHG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Producer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unlisted Contact</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Originator__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Originator</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Interactions</relationshipLabel>
        <relationshipName>Interactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Tax_Id__c</fullName>
        <label>Provider Tax ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Interaction</label>
    <nameField>
        <displayFormat>INT-{0}</displayFormat>
        <label>Interaction ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Interaction_Alert__c.object
<CustomObject>
    <fields>
        <fullName>Alert__c</fullName>
        <description>Alert Parent record to this record</description>
        <label>Alert</label>
        <referenceTo>Alert__c</referenceTo>
        <relationshipLabel>Interaction Alerts</relationshipLabel>
        <relationshipName>Interaction_Alerts</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ID_Number__c</fullName>
        <label>ID Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Interaction__c</fullName>
        <description>Parent Interaction record to this record</description>
        <label>Interaction</label>
        <referenceTo>Interaction__c</referenceTo>
        <relationshipLabel>Interaction Alerts</relationshipLabel>
        <relationshipName>Interaction_Alerts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Intercation_Alert_Unique_Id_del__c</fullName>
        <externalId>true</externalId>
        <label>Intercation Alert Unique Id</label>
        <length>253</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Interaction Alert</label>
    <nameField>
        <displayFormat>IA-{000000000}</displayFormat>
        <label>Interaction Alert ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interaction Alerts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ACETProducerDetailController.cls
public with sharing class ACETProducerDetailController
{
    public ACETProducerResult producerDetailresult { get; set;} 
    public id contactid{ get; set;}
    public String interactionId{ get; set;}
     public String hpAdditionInfoStr {get{
        return JSON.serialize(AdditionalInfo);
    }set;}
    public String Id { get; set;}
    public Interaction__c Interaction { get; set;}
    public Contact Subject { get; set;}
    public ACETHighlightsPanelAdditionalInfo AdditionalInfo { get; set;}
    public list<Alert__c> lstMemAlert{ get; set;}
    public list<Alert__c> lstProducerAlert{ get; set;}//added by Harish for Alert
    public String SourceOriginator { get; set;}
    public ACETCallTopicsDataWrapper wrapper { get; set;}   
    public String producerId { get; set; }   
    public List<SelectOption> contactTypeOptions { get; set;}
    public String contactType { get; set;}
    public String originatorName { get; set;}
    public String contactName { get; set;}
    public boolean isShowALert{get;set;}
    //continuation web call
    ACETGetProducerAdapterWebservice ACETPDWS;
    
    public ACETProducerDetailController(){
        producerId = ApexPages.currentPage().getParameters().get('ProducerId');
        Id = ApexPages.currentPage().getParameters().get('Id');
        interactionId = ApexPages.currentPage().getParameters().get('InteractionId'); 
        system.debug('InteractionId: ' + InteractionId); 
        contactId  = null;
        system.debug('contactId: ' + contactId); 
        contactTypeOptions = new List<SelectOption>();
        contactTypeOptions.add(new SelectOption('Broker', 'Broker'));
        contactTypeOptions.add(new SelectOption('General Agent' , 'General Agent'));        
        List<Interaction__c> InteractionList = [SELECT id, name,Originator__c,Interaction_Type__c,Originator_Type__c,Contact_Name__c,
                                Originator__r.Name  from Interaction__c where id =: interactionId];
        if(InteractionList.size() > 0){
            Interaction = InteractionList[0];
        } 
        try{
            Interaction = ACETMemberQueryUtil.queryInteraction(Interaction.Id);
            Subject = ACETMemberQueryUtil.queryContact(Interaction.Originator__c);
        }catch(Exception e){} 
        AdditionalInfo = new ACETHighlightsPanelAdditionalInfo();
        AdditionalInfo.producerSubject = Interaction.Originator__r.Name;
        AdditionalInfo.producerOriginator =  Interaction.Originator__r.Name;
        AdditionalInfo.producerId = Interaction.Originator__r.EID__c;
        hpAdditionInfoStr = JSON.serialize(AdditionalInfo); 
        lstProducerAlert = new list<Alert__c>();
        
    }
    public void updateContact()
    {
        isShowALert = true;
        if(Interaction.Contact_Name__c != contactName)
        {
            Interaction.Contact_Name__c = contactName;
            if(contactType == 'Broker')
            {
                Interaction.Caller_Type__c = 'Broker';
            }else
            {
                Interaction.Caller_Type__c = 'General Agent';
            }
            update Interaction;
            
            AdditionalInfo.producerName = contactName + ' - '+Interaction.Caller_Type__c;
            hpAdditionInfoStr = JSON.serialize(AdditionalInfo);
        }
    
    }
        public void getNumberOfProducerAlert(){
            ACETInteractionHighlightsPanelController alertNumber = new ACETInteractionHighlightsPanelController();
             System.debug('list of interaction'+interaction);
            if(interaction != null){
                lstProducerAlert = alertNumber.getNoAlert('Producer',interaction.Originator__r.EID__c,interaction.Originator__r.Tax_ID__c);
                System.debug('list of producer Alert'+lstProducerAlert);
                if(!lstProducerAlert.IsEmpty()){
                    list<Interaction_Alert__c> lstIntAlert = new list<Interaction_Alert__c>();
                    for(Alert__c varalert : lstProducerAlert){
                        Interaction_Alert__c intAlert = new Interaction_Alert__c();
                        intAlert.Alert__c = varAlert.id;
                        intAlert.Interaction__c = interaction.id;
                        intAlert.ID_Number__c = interaction.Originator__r.EID__c;// added by vishakha 11/30 for US442332
                        intAlert.Intercation_Alert_Unique_Id_del__c = String.valueof(varAlert.id)+String.valueof(Interaction.id)+ Interaction.Originator__r.EID__c;
                        lstIntAlert.add(intAlert); 
                    }
                    try{
                        Upsert lstIntAlert Intercation_Alert_Unique_Id_del__c ;//added by vishakha 12/09
                    }
                    Catch(DMLException ex){
                        ApexPages.addmessage(new ApexPages.message(ApexPages.severity.Error,'Exception during Insertion Interaction Alert.'));
                    }
                }
            }
        }
  
    
    public void updateInteraction(){
        if(Interaction != null){
            Interaction.Contact_Name__c = contactName;
            Interaction.Caller_Type__c = contactType;            
            update Interaction;
        }
    }    
   
         
    public List<Case> getCaseHistory(){
        String Id = ApexPages.currentPage().getParameters().get('Id');
        List<Case> cases = [select CaseNumber, Contact.Name, ContactId, CreatedBy.Name, CreatedDate, Topic__c, Status, Originator_Type__c, Interaction_Type__c, Interaction__c,Rollup_Fulfillment__c,(SELECT Id, Name FROM Create_Letters__r) from Case where ContactId =: Subject.id order by CreatedDate desc limit 500];
        return cases;
    }
    
    public Object CallGetProducerWS1(){
    system.debug('Entery for callGetproducerWS call');
        Continuation PageLoadContinuation;                
        ACETPDWS = new ACETGetProducerAdapterWebservice();
        PageLoadContinuation = ACETPDWS.StartRequest(producerId,'PDWebserviceCallBack',null);
         System.debug('Entery PageLoadContinuation'+PageLoadContinuation);
        return PageLoadContinuation;
    }
    
    public PageReference PDWebserviceCallBack(){
        ACETWSCalloutResult GetProducerResponse;
        isShowALert = true;
        system.debug('Entery for PDWebserviceCallBack call');
        GetProducerResponse = ACETPDWS.ProcessResponse(ACETPDWS.RequestLabel);
         system.debug('Entery for GetProducerResponse call'+GetProducerResponse);
        if(GetProducerResponse.Success){
            try{
               producerDetailresult = (ACETProducerResult)GetProducerResponse.Response;
               getNumberOfProducerAlert();
            }catch(Exception ex){
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Error, system.Label.ACETUnexpectedErrorMessage));
            }
        }
        return null; 
    } 
    
    public List<SelectOption> getCallTopicOptions()
    {
        List<SelectOption> callTopics = new List<SelectOption>();
        callTopics = ACETCallTopicsPicklistUtility.getCallTopicOptions('Producer Detail', Interaction.Originator_Type__c);
        return callTopics;
    }

}