src/objects/Bookmark_Links__c.object
<CustomObject>
    <description>This object is used to store bookmark links displayed on the application footer. This object will be business enabled.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Must be true for bookmark link to active</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Display_Name__c</fullName>
        <description>Display name of links</description>
        <label>Display Name</label>
        <length>225</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Profiles__c</fullName>
        <description>Profiles enabled for each link</description>
        <label>Profiles</label>
        <picklist>
            <picklistValues>
                <fullName>ACET Provider</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ACET Member</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ACET System Administrator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>System Administrator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ACET CSO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ACET CSS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ACET DCSM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ACET Rapid Responder Team</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ACET EB Agent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ECM Back Office Agent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Research User</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>URL__c</fullName>
        <description>Hyperlink URL</description>
        <label>URL</label>
        <type>Url</type>
    </fields>
    <label>Bookmark Link</label>
    <nameField>
        <displayFormat>BL-{0000}</displayFormat>
        <label>Bookmark Link Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bookmark Links</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ACETBookmarkLinksControllerTest.cls
@istest
private class ACETBookmarkLinksControllerTest{

static testMethod void testACETBookmarkLinksController (){

       User u = [select id,profile.name from user where profile.name = 'System Administrator' and isactive = true limit 1];
       PageReference pageRef = Page.ACETBookmarkLinks;
       Test.setCurrentPage(pageRef);
    
     
      
      List<Bookmark_Links__c > lstbookmark= new List<Bookmark_Links__c >();
        
        for(Integer i=0;i<5;i++) {
            Bookmark_Links__c a = new Bookmark_Links__c (Display_Name__c = 'test' + i,Profiles__c = 'System Administrator',URL__c = 'www.test.com',Active__c=true);
            lstbookmark.add(a);
        }
        insert lstbookmark;
      Test.startTest();
       System.runAs(u) {
       ACETBookmarkLinksController bookmark  = new ACETBookmarkLinksController();
       System.assertEquals(bookmark.lstBookmarkLinks.size(),lstbookmark.size());
       }
       Test.stopTest();
      
}

}