src/objects/Bookmark_Links__c.object
<CustomObject>
    <description>This object is used to store bookmark links displayed on the application footer. This object will be business enabled.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Must be true for bookmark link to active</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Display_Name__c</fullName>
        <description>Display name of links</description>
        <label>Display Name</label>
        <length>225</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Profiles__c</fullName>
        <description>Profiles enabled for each link</description>
        <label>Profiles</label>
        <picklist>
            <picklistValues>
                <fullName>ACET Provider</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ACET Member</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ACET System Administrator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>System Administrator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ACET CSO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ACET CSS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ACET DCSM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ACET Rapid Responder Team</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ACET EB Agent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ECM Back Office Agent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Research User</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>URL__c</fullName>
        <description>Hyperlink URL</description>
        <label>URL</label>
        <type>Url</type>
    </fields>
    <label>Bookmark Link</label>
    <nameField>
        <displayFormat>BL-{0000}</displayFormat>
        <label>Bookmark Link Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bookmark Links</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ACETBookmarkLinksController.cls
public with sharing class ACETBookmarkLinksController {
    
   
    public List<Bookmark_Links__c> lstBookmarkLinks{get;set;}
    
    
    
    public ACETBookmarkLinksController()
    {
            Id profileId=userinfo.getProfileId();
            String profileName=[Select Id,Name from Profile where Id=:profileId].Name;
            system.debug('ProfileName'+profileName);
            
            lstBookmarkLinks = [select name,Display_Name__c,Profiles__c,URL__c,Active__c from Bookmark_Links__c where Active__c = true and Profiles__c includes (:profileName) order by Display_Name__c];  
    } 
    
    
 }