src/objects/Call_Topic_Access__c.object
<CustomObject>
    <fields>
        <fullName>Except_To_Roles__c</fullName>
        <description>roles from this list is not able to access the call topic</description>
        <label>Except To Roles</label>
        <picklist>
            <picklistValues>
                <fullName>ACET Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ACET Supervisor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ACET Agent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ACET CSO Agent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ACET CSS Agent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ACET DCSM Agent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ACET Rapid Responder</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Back Office Site Director-Member CCT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Back Office Manager-Member CCT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Back Office Supervisor/Coach/SME-Member CCT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Back Office Agent-Member CCT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Back Office Site Director-Member Rework</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Back Office Manager-Member Rework</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Back Office Supervisor/Coach/SME-Member Rework</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Back Office Agent-Member Rework</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Back Office Site Director-Provider Clerical</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Back Office Manager-Provider Clerical</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Back Office Supervisor/Coach/SME-Provider Clerical</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Back Office Agent-Provider Clerical</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Back Office Site Director-Provider Rework</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Back Office Manager-Provider Rework</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Back Office Supervisor/Coach/SME-Provider Rework</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Back Office Agent-Provider Rework</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Limit_To_Roles__c</fullName>
        <description>Only roles from the list can access to the calltopic</description>
        <label>Limit To Roles</label>
        <picklist>
            <picklistValues>
                <fullName>ACET Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ACET Supervisor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ACET Agent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ACET CSO Agent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ACET CSS Agent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ACET DCSM Agent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ACET Rapid Responder</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Back Office Site Director-Member CCT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Back Office Manager-Member CCT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Back Office Supervisor/Coach/SME-Member CCT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Back Office Agent-Member CCT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Back Office Site Director-Member Rework</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Back Office Manager-Member Rework</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Back Office Supervisor/Coach/SME-Member Rework</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Back Office Agent-Member Rework</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Back Office Site Director-Provider Clerical</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Back Office Manager-Provider Clerical</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Back Office Supervisor/Coach/SME-Provider Clerical</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Back Office Agent-Provider Clerical</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Back Office Site Director-Provider Rework</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Back Office Manager-Provider Rework</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Back Office Supervisor/Coach/SME-Provider Rework</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Back Office Agent-Provider Rework</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <label>Call Topic Access</label>
    <nameField>
        <label>Call Topic Access Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Call Topic Access</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TTS_Access__c.object
<CustomObject>
    <description>access control to type and sub type from profile and role</description>
    <fields>
        <fullName>Except_To_Roles__c</fullName>
        <label>Except To Roles</label>
        <picklist>
            <picklistValues>
                <fullName>ACET Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ACET Supervisor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ACET Agent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ACET CSO Agent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ACET CSS Agent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ACET DCSM Agent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ACET Rapid Responder</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Back Office Site Director-Member CCT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Back Office Manager-Member CCT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Back Office Supervisor/Coach/SME-Member CCT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Back Office Agent-Member CCT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Back Office Site Director-Member Rework</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Back Office Manager-Member Rework</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Back Office Supervisor/Coach/SME-Member Rework</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Back Office Agent-Member Rework</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Back Office Site Director-Provider Clerical</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Back Office Manager-Provider Clerical</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Back Office Supervisor/Coach/SME-Provider Clerical</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Back Office Agent-Provider Clerical</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Back Office Site Director-Provider Rework</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Back Office Manager-Provider Rework</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Back Office Supervisor/Coach/SME-Provider Rework</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Back Office Agent-Provider Rework</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Limit_To_Profiles__c</fullName>
        <label>Limit To Profiles</label>
        <picklist>
            <picklistValues>
                <fullName>ACET EB Agent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ACET Member</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ACET Provider</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ECM Back Office Agent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Research User</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NA</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Limit_To_Roles__c</fullName>
        <label>Limit To Roles</label>
        <picklist>
            <picklistValues>
                <fullName>ACET Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ACET Supervisor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ACET Agent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ACET CSO Agent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ACET CSS Agent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ACET DCSM Agent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ACET Rapid Responder</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Back Office Site Director-Member CCT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Back Office Manager-Member CCT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Back Office Supervisor/Coach/SME-Member CCT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Back Office Agent-Member CCT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Back Office Site Director-Member Rework</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Back Office Manager-Member Rework</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Back Office Supervisor/Coach/SME-Member Rework</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Back Office Agent-Member Rework</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Back Office Site Director-Provider Clerical</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Back Office Manager-Provider Clerical</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Back Office Supervisor/Coach/SME-Provider Clerical</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Back Office Agent-Provider Clerical</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Back Office Site Director-Provider Rework</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Back Office Manager-Provider Rework</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Back Office Supervisor/Coach/SME-Provider Rework</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Back Office Agent-Provider Rework</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Topic__c</fullName>
        <globalPicklist>Topic</globalPicklist>
        <label>Topic</label>
        <type>Picklist</type>
    </fields>
    <label>TTS Access</label>
    <nameField>
        <displayFormat>TTSA-{000000000}</displayFormat>
        <label>TTSA #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TTS Access</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ACETCallTopicsPicklistUtility.cls
public with sharing class ACETCallTopicsPicklistUtility {	
	
	public static String getTTSFilter(String callTopic){
		return JSON.serialize(getTTSFilterMap(callTopic)).replace('\'', '&#x27;');		
	}
	
	//get the limited type and subtype list based on profile and role
	public static Map<String, String> getTTSFilterMap(String callTopic){
		Map<String, string> accMap = new Map<String, String>();
		
		String userRoleName = ACETUtility.GetUserRoleName();
		String userProfileName = ACETUtility.GetUserProfileName();
						
		List<TTS_Access__c> acceses = (List<TTS_Access__c>)ACETQueryUtil.query(null,'TTS_Access__c', 'Topic__c = \'' + callTopic + '\'', null);
		for(TTS_Access__c acc : acceses){
			Boolean hasAccess = false;
			//do not have role filter for now
			//if(String.isEmpty(acc.Limit_To_Roles__c) || (userRoleName != null && acc.Limit_To_Roles__c.contains(userRoleName))){
				//hasAccess = true;	
			//}
			
			//if(String.isEmpty(acc.Except_To_Roles__c) || (userRoleName == null || acc.Except_To_Roles__c.contains(userRoleName))){
				//hasAccess = true;	
			//}
									
			if(acc.Limit_To_Profiles__c != null && acc.Limit_To_Profiles__c.contains(userProfileName)){
				hasAccess = true;	
			}
			
			//if(!String.isEmpty(acc.Except_To_Profiles__c) && (acc.Except_To_Profiles__c.contains(userProfileName))){
				//hasAccess = false;	
			//}
			
			if(!String.isEmpty(acc.Type__c) && hasAccess){			
				if(accMap.get(acc.Type__c) == null){
					accMap.put(acc.Type__c, (acc.Subtype__c == null? '*' : acc.Subtype__c));
				}else{
					//if 2 configuration with sampe type are found, one with sub type empty and one with sub type populated
					//the first configuration overwrites the second one as first one means type level access is sepcified					
					if(accMap.get(acc.Type__c) == '*' || String.isEmpty(acc.Subtype__c)){
						//access control on type level
						accMap.put(acc.Type__c, '*');	
					}else{
						//access control on sub type level
						accMap.put(acc.Type__c, accMap.get(acc.Type__c) + ';' + acc.Subtype__c);		
					}										
				}	
			}			
		}
						
		return accMap;
	}
	
	
	public static List<String> getCallTopics(String detailPageName, String originatorType){
		List<Call_Topic_Access__c> accesses = (List<Call_Topic_Access__c>)ACETQueryUtil.query(null,'Call_Topic_Access__c', 'Detail_Page__c INCLUDES(' + '\'' + detailPageName + '\')', null);
		
		String userRoleName = ACETUtility.GetUserRoleName();
		
		List<String> result = new List<String>();
		for(Call_Topic_Access__c acc : accesses){
			if(!String.isEmpty(acc.Limit_To_Roles__c) && (userRoleName == null || !acc.Limit_To_Roles__c.contains(userRoleName))){
				continue;	
			}
			
			if(!String.isEmpty(acc.Except_To_Roles__c) && (userRoleName != null && acc.Except_To_Roles__c.contains(userRoleName))){
				continue;	
			}
			
			if(!String.isEmpty(acc.Originator_Type__c) && (originatorType == null || !acc.Originator_Type__c.contains(originatorType))){
				continue;	
			}
														
			result.add(acc.Call_Topic__c);			
		}
		
		return result;	
	}
	
	public static List<SelectOption> getCallTopicOptions(String detailPageName, String originatorType){
		List<String> callTopics = getCallTopics(detailPageName, originatorType);
		
		callTopics.sort();
		List<SelectOption> options = new List<SelectOption>();
		for(String callTopic : callTopics){
			options.add(new SelectOption(callTopic, callTopic));
		}
		return options;	
	}
	
	public static List<String> getCallTopics(String detailPageName){
		List<Call_Topic_Access__c> accesses = (List<Call_Topic_Access__c>)ACETQueryUtil.query(null,'Call_Topic_Access__c', 'Detail_Page__c INCLUDES(' + '\'' + detailPageName + '\')', null);
		
		List<String> result = new List<String>();
		for(Call_Topic_Access__c acc : accesses){
			result.add(acc.Call_Topic__c);
		}
		
		return result;	
	}
	
	public static List<SelectOption> getCallTopicOptions(String detailPageName){
		List<String> callTopics = getCallTopics(detailPageName);
		
		callTopics.sort();
		List<SelectOption> options = new List<SelectOption>();
		for(String callTopic : callTopics){
			options.add(new SelectOption(callTopic, callTopic));
		}
		return options;	
	}		   
      
}