src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Interaction__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Interaction</label>
        <referenceTo>Interaction__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Originator_Type__c</fullName>
        <formula>TEXT(Interaction__r.Originator_Type__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Originator Type</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>EID__c</fullName>
        <externalId>true</externalId>
        <label>EID</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>NPI__c</fullName>
        <label>NPI</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tax_ID__c</fullName>
        <label>Tax ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Interaction__c.object
<CustomObject>
    <fields>
        <fullName>Contact_Name__c</fullName>
        <label>Contact Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Highlight_Panel_GroupInfo__c</fullName>
        <label>Highlight Panel GroupInfo</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>NPI__c</fullName>
        <label>NPI</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Originator_Type__c</fullName>
        <label>Originator Type</label>
        <picklist>
            <picklistValues>
                <fullName>Provider</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Member</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Third Party</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Broker</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Group/Employer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>General Agent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UHG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Producer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unlisted Contact</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Originator__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Originator</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Interactions</relationshipLabel>
        <relationshipName>Interactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Tax_Id__c</fullName>
        <label>Provider Tax ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Interaction</label>
    <nameField>
        <displayFormat>INT-{0}</displayFormat>
        <label>Interaction ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ISL_Webservice_Config__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Store ISL Webservice configuration values</description>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>ISL Webservice Config</label>
</CustomObject>

src/classes/TestDataFactory.cls
@isTest
public class TestDataFactory{
    //Test Data//
    public static Contact createContact(){
        Contact con = new Contact();
        con.FirstName = 'TestFname';
        con.lastname = 'TestLName';
        con.Tax_ID__c = '123456';
        con.NPI__c = '123457';
        //con.EID__c = ''+randomWithLimit(4000);
        insert con;
        
        return con;
    }
    public static Contact createContactwithEID(){
        Contact con = new Contact();
        con.FirstName = 'Test Fname';
        con.lastname = 'Test LName';
        con.Tax_ID__c = '123456';
        con.NPI__c = '123457';
        con.EID__c = ''+randomWithLimit(4000);
        insert con;
        
        return con;
    }
    public static Interaction__c createInteraction () {
        String JSONStr = '{"UHCBS":"","GroupN":"Test Group Name","GroupStatus":"Active","ServiceTeam":"NY Large","EffectiveStartDate":"3/1/2016","RiskManagement":"Rating Method","RatingMethod":"Support","RenewalDate":"3/1/2016","RelationshipType":"Mother","groupSName":"Test GroupName"}';
        Interaction__c inte = new Interaction__c();
        inte.Contact_Name__c = 'Text Iname';
        inte.Originator__c = createContact().id;
        inte.Originator_Type__c = 'Member';
        inte.Highlight_Panel_GroupInfo__c = JSONStr;
        insert inte;
        
        return inte;
    }
    public static string createACETHighlightsPanelAdditionalInfo(){
        ACETHighlightsPanelAdditionalInfo jsonReq = new ACETHighlightsPanelAdditionalInfo();
        jsonReq.Relationship='Test';   
        jsonReq.SitusState='Test';
        jsonReq.DOB='09/28/2016';
        jsonReq.EndDate='09/28/2016';
        jsonReq.EffectiveDate='09/28/2016';
        jsonReq.PolicyNumber='12345';
        jsonReq.GroupName='Test';
        jsonReq.Product='Test';
        jsonReq.ProductType='Test';
        jsonReq.Network='Test';
        jsonReq.ConsumerAccountIndicator='Test';
        
        String additionalInfoStr  = JSON.serialize(jsonReq);
        return additionalInfoStr;
    }
     public static ISL_Webservice_Config__c CreateISLWebserviceCS(String name,String value) {
        ISL_Webservice_Config__c cs = new ISL_Webservice_Config__c();
        cs.name = name;
        cs.value__c = value;
        return cs;
    }
    public static User getUser(String profile){
        Profile p = [SELECT Id FROM Profile WHERE Name=:profile]; 
      User u = new User(Alias = 'standt', Email='standarduser@testorg.com', 
      EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
      LocaleSidKey='en_US', ProfileId = p.Id, 
      TimeZoneSidKey='America/Los_Angeles', UserName= profile.deleteWhitespace()+'@testorg.com');
      
      return u;     
    }
    
    public static Integer randomWithLimit(Integer upperLimit){
        Integer rand = Math.round(Math.random()*1000);
        return Math.mod(rand, upperLimit);
    }
  public static List<Case> createCases(Integer numCase) {
        List<Case> caseList = new List<Case>();
        for(Integer iCnt =0; icnt<numCase; iCnt++){
            Case cas = new Case();
            caseList.add(cas);
        }

        return caseList;
    }
    
     public static Case createCase(){
        Case cas = new Case();
        cas.Status = 'Open';
        insert cas;
        return cas;
    }
    
}