src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Interaction__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Interaction</label>
        <referenceTo>Interaction__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Originator_Type__c</fullName>
        <formula>TEXT(Interaction__r.Originator_Type__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Originator Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tst_Date_Field__c</fullName>
        <inlineHelpText>This is the sample date field</inlineHelpText>
        <label>Date Field</label>
        <type>Date</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Interaction__c.object
<CustomObject>
    <fields>
        <fullName>Originator_Type__c</fullName>
        <label>Originator Type</label>
        <picklist>
            <picklistValues>
                <fullName>Provider</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Member</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Third Party</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Broker</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Group/Employer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>General Agent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UHG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Producer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unlisted Contact</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Originator__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Originator</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Interactions</relationshipLabel>
        <relationshipName>Interactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Interaction</label>
    <nameField>
        <displayFormat>INT-{0}</displayFormat>
        <label>Interaction ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interactions</pluralLabel>
    <recordTypes>
        <fullName>Phone</fullName>
        <active>true</active>
        <label>Phone</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ACETMemberNotFoundController.cls
public with sharing class ACETMemberNotFoundController {
    public String InteractionType { get; set; }
    public String EmployerName {get;set;}
    public String GroupNumber {get;set;}
    public Date dateOfBirth { get; set; }
    public String LastName { get; set; }
    public String FirstName { get; set; }
    public String memberId { get; set; }
    public String zipcode { get; set; }
    public String State {get;set;}
    public String PhoneNumber {get;set;}
    public Case StartDate{get;set;}
    
    public Interaction__c  Interaction{get;set;}
    
    public ACETMemberNotFoundController() {
        StartDate = new Case();
        Interaction = new Interaction__c();
        InteractionType = ApexPages.currentPage().getParameters().get('IT');        
        string dateString = ApexPages.currentPage().getParameters().get('DOB');
        if(dateString != '' && dateString != null){            
            StartDate.tst_Date_Field__c = date.parse(dateString);
            dateOfBirth = StartDate.tst_Date_Field__c;
        }    
        memberId    = ApexPages.currentPage().getParameters().get('MID');
        zipcode     = ApexPages.currentPage().getParameters().get('zip');
        LastName    = ApexPages.currentPage().getParameters().get('LN');
        firstName   = ApexPages.currentPage().getParameters().get('FN');
        State       = ApexPages.currentPage().getParameters().get('ST');
        PhoneNumber = ApexPages.currentPage().getParameters().get('PH');
        EmployerName = ApexPages.currentPage().getParameters().get('EN');
        GroupNumber    = ApexPages.currentPage().getParameters().get('GN');
        
        
       /* system.debug(LoggingLevel.INFO, 'InteractionType: ' + InteractionType + ', ContactName: ' + ContactName + ', LastName: ' + LastName + ', FirstName: ' + FirstName);
        system.debug(LoggingLevel.INFO, ', TaxId: ' + TaxId + ', Npi: ' + Npi  + ', phoneNumber: ' + phoneNumber);*/
    }
    
    public PageReference RedirectFromMemberNotFound() {
        PageReference pageRef ;
        // logic for lastname + Phone number to be addded
        try {                        
            system.debug('all parameter : ' + InteractionType+memberId+zipcode+LastName+firstName+State+PhoneNumber+EmployerName+GroupNumber);   

            Interaction =  ACETMemberQueryUtil.queryInteraction(InteractionType, Label.ACETProviderNotFoundOriginatorType,EmployerName, LastName, firstName, phoneNumber,StartDate.tst_Date_Field__c,state,zipcode,groupnumber);
            insert Interaction;
            
            system.debug(LoggingLevel.INFO, 'Interaction for Manual Member Created : ' + Interaction);            
            //string urlstr = '/apex/acetmemberdetail?lastName='+ Interaction.originator__r.Lastname + '&firstName=' + Interaction.originator__r.firstname + '&SRK=' + '&subjectdob=' +  Interaction.originator__r.birthdate + '&sourceOriginator= '+ Interaction.Originator_Type__c+ '&InteractionId='+ Interaction.Id +'&mnf=1&core.apexpages.devmode.url=1' ;
            //
            //pageRef = new PageReference(urlstr);
            pageRef = page.acetmemberdetail;
            pageRef.getParameters().put('InteractionId',Interaction.Id);
            //pageRef.getParameters().put('lastName',Interaction.originator__r.Lastname);
            //pageRef.getParameters().put('firstName',Interaction.originator__r.firstname);
            //pageRef.getParameters().put('subjectdob',date.valueOf(Interaction.originator__r.birthdate));
            pageRef.getParameters().put('mnf','1');
            //+'&IT='+InteractionType+'&LN='+lastName+'&FN='+firstName+'&PH='+phoneNumber+'&MID='+memberId+'&DOB='+dateOfBirth);
            pageRef.setRedirect(True);
        }
        catch (Exception ex) {
            system.debug(LoggingLevel.INFO, 'Error creating Interaction. Details: ' + ex.getMessage());
            pageRef=null;
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Error, system.Label.ACETUnexpectedErrorMessage));
        }
       
        return pageRef;
    }
}