src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Other_Originator__c</fullName>
        <label>Other Originator</label>
        <picklist>
            <picklistValues>
                <fullName>Attorney</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Caregiver</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Collection Agency</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Family/Friend/Spouse</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Insurance Carrier</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Parent/Guardian</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pharmacy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prospective Member</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Provider</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reporter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Representative</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>State Regulatory Agent/Government Agency</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UHG Employee</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Interaction__c.object
<CustomObject>
    <fields>
        <fullName>Contact_Name__c</fullName>
        <label>Contact Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Third_Party__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Third Party</label>
        <referenceTo>Third_Party__c</referenceTo>
        <relationshipLabel>Interactions (Third Party)</relationshipLabel>
        <relationshipName>Interactions1_del</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Interaction</label>
    <nameField>
        <displayFormat>INT-{0}</displayFormat>
        <label>Interaction ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Third_Party__c.object
<CustomObject>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FullName__c</fullName>
        <label>Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Group_Name__c</fullName>
        <label>Group Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone_Number__c</fullName>
        <label>Phone Number</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>Third Party</label>
    <nameField>
        <label>Last Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Third Parties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Third_Party_Originator__c.object
<CustomObject>
    <description>to store the originator association between a third party and a subject</description>
    <fields>
        <fullName>Other_Originator__c</fullName>
        <label>Other Originator</label>
        <picklist>
            <picklistValues>
                <fullName>Attorney</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Caregiver</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Collection Agency</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Family/Friend/Spouse</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Insurance Carrier</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Parent/Guardian</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pharmacy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prospective Member</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Provider</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reporter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Representative</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>State Regulatory Agent/Government Agency</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UHG Employee</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Subject</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Third_Party_Relationships</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Third_Party__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Third Party</label>
        <referenceTo>Third_Party__c</referenceTo>
        <relationshipName>Third_Party_Relationships</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Third Party Originator</label>
    <nameField>
        <label>Third Party Relationship Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Third Party Originators</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ACETThirdPartyContactsController.cls
/**
 * @name         :  ACETThirdPartyContactsController
 * @description  :  Controller for ACETThirdPartyComponent. this component is responsible for fetching, updating and creating third parties.
 * @author       :  Bhanu Jain
 * @createddate  :  20/11/2016
 **/

public class  ACETThirdPartyContactsController {
    
    public ACETCallTopicsDataWrapper wrapper {get;set;}
    public List<Third_Party_Originator__c> TPOriginatorList {get;set;}
    public Third_Party_Originator__c TPOriginator {get;set;}
    public Contact TPOriginatortRelContact {get;set;}
    public String SubjectId{get;set;}
    public boolean showNoThirdPartyError {get;set;}
    public ACETHighlightsPanelAdditionalInfo additionalInfo {get;set;}
    public String additionalInfoStr {get;set;} 
    public String SourceOriginator{get;set;}
    public Interaction__c interaction {get;set;}
    public Map<String,Third_Party_Originator__c> MaptpoIDvstpo {get;set;}
    public String tpliststr {get;set;}
    public ACETThirdPartyContactsController (){
        showNoThirdPartyError = false;
        TPOriginatortRelContact = new Contact();
        TPOriginator = new Third_Party_Originator__c();
        TPOriginator.third_party__r = new Third_Party__c(); 
            
    }
/**
* @name         :   getThirdPartyList
* @description  :   This method/action function is responsible getting the third party list associated to current subject
* @param        :   void   
* @return       :   void
* @author       :   Bhanu Jain
* @createddate  :   20/11/2016
* @lastmodifiedby:  
**/     
    public void getThirdPartyList(){
        TPOriginatorList = [select id,Third_Party__r.First_Name__c,Third_Party__r.FullName__c,Third_Party__r.Phone_Number__c ,Third_Party__r.Name, Name, Third_Party__r.Group_Name__c, other_originator__c from Third_Party_Originator__c where Subject__c =:SubjectId ORDER BY Third_Party__r.Name ASC];
        
        if(TPOriginatorList.isEmpty()){
            showNoThirdPartyError =true;
            TPOriginator = new Third_Party_Originator__c();
            TPOriginator.Third_Party__r = new Third_Party__c();
        }else{
                    tpliststr = JSON.serialize(TPOriginatorList);
            showNoThirdPartyError = false;
        }        
        
    }
/**
* @name         :   updatehighlightPanelStr
* @description  :   This method/action function will be called from UI to variable to with selected third party. So that it can be used to display in highlisht panel.
* @param        :   void   
* @return       :   void
* @author       :   Bhanu Jain
* @createddate  :   20/11/2016
* @lastmodifiedby:  
**/    
    public void updatehighlightPanelStr(){
        //ACETHighlightsPanelAdditionalInfo hpInfo = (ACETHighlightsPanelAdditionalInfo )JSON.deserialize(highlightPanelStr,ACETHighlightsPanelAdditionalInfo.class);
        String selectedTPId = ApexPages.currentPage().getParameters().get('selectedRow');
        system.debug('row id >> '+TPOriginatorList);
        for(Third_Party_Originator__c tpo : TPOriginatorList){

            if(tpo.third_party__c == selectedTPId ){
                additionalInfo.OriginatorRelationship = tpo.Name;
                additionalInfo.RelationshipType = tpo.Name;
                
                SourceOriginator = tpo.third_party__r.First_Name__c;
                //update Interaction obj
                interaction.Third_Party__r= tpo.third_party__r;
                interaction.Third_Party__c= tpo.third_party__c;
                Interaction.Contact_Name__c = tpo.third_party__r.FullName__c;
                
            }
        }
        additionalInfoStr = JSON.serialize(additionalInfo);
        upsert interaction;
//        interaction = ACETMemberQueryUtil.queryInteraction(interaction.Id);
        system.debug('interaction after updateHighlightPanel'+interaction);
        //additionalInfo.OriginatorRelationship = 'testing';
        
    }
        /**
* @name         :   addNewThirdParty
* @description  :   This method/action function will create new  the third party record and its junction. Also will refresh the third party list which is displayed on UI.
* @param        :   void   
* @return       :   void
* @author       :   Bhanu Jain
* @createddate  :   20/11/2016
* @lastmodifiedby:  
**/
    public void addNewThirdParty(){
        //create new third party
        if(TPOriginatorList == Null)
        {
            TPOriginatorList = new List<Third_Party_Originator__c>();
        }
        system.debug('TPOriginator >> '+TPOriginator);
        Third_Party__c newThirdParty = new Third_Party__c();
         newThirdParty.first_name__c = TPOriginator.third_party__r.first_name__c;
        newThirdParty.name = TPOriginator.third_party__r.name;
        newThirdParty.Phone_Number__c  = TPOriginator.third_party__r.Phone_Number__c ;
        newThirdParty.Group_Name__c = TPOriginator.third_party__r.Group_Name__c;
        insert newThirdParty;
        
        
        
        TPOriginator= new Third_Party_Originator__c();
        TPOriginator.subject__c =SubjectId;
        TPOriginator.third_party__c = newThirdParty.Id;
        TPOriginator.third_party__r = newThirdParty;
        TPOriginator.name = TPOriginatortRelContact.other_originator__c;
        insert TPOriginator;
        
        showNoThirdPartyError =false;
        TPOriginatorList.add(TPOriginator);
        
        getThirdPartyList();
                
    }
/**
* @name         :   updateThirdParty
* @description  :   This method/action function will update the third party objectand its junction. Also will refresh the third party list which is displayed on UI.
* @param        :   void   
* @return       :   void
* @author       :   Bhanu Jain
* @createddate  :   20/11/2016
* @lastmodifiedby:  
**/    
    public void updateThirdParty(){
        system.debug('TPOriginator >> '+TPOriginator);
        TPOriginator.name= TPOriginatortRelContact.other_originator__c;
        Third_Party__c thirdPartyObj = TPOriginator.third_party__r;
        
        upsert TPOriginator.third_party__r;
        upsert TPOriginator;
           for(Third_Party_Originator__c tpo : TPOriginatorList){
        
                    if(tpo.third_party__c == TPOriginator.third_party__c){
                        tpo = TPOriginator;
                    }
                }
           getThirdPartyList();             
           tpliststr = JSON.serialize(TPOriginatorList);    
            
    }
/**
* @name         :   updateUI
* @description  :   This method/action function is responsible getting the third party list associated to current subject
* @param        :   void   
* @return       :   void
* @author       :   Bhanu Jain
* @createddate  :   20/11/2016
* @lastmodifiedby:  
**/    
    public void updateUI(){
    
    }
/**
* @name         :   updateInteraction
* @description  :   This method/action function will update current interaction with selected third party contact.
* @param        :   void   
* @return       :   void
* @author       :   Bhanu Jain
* @createddate  :   20/11/2016
* @lastmodifiedby:  
**/    
    public void updateInteraction(){
        upsert interaction;
    }
/**
* @name         :   populateEditPopup
* @description  :   This method/action function is responsible for setting selected third party object which will be populated in edit pop up.
* @param        :   void   
* @return       :   void
* @author       :   Bhanu Jain
* @createddate  :   20/11/2016
* @lastmodifiedby:  
**/    
    public void populateEditPopup(){
        String selectedTPId = ApexPages.currentPage().getParameters().get('selectedEditRow');
        system.debug(JSON.serialize(TPOriginatorList));
        system.debug(JSON.serialize(TPOriginatorList));
        for(Third_Party_Originator__c tpo : TPOriginatorList){
            if(tpo.third_party__c == selectedTPId ){
                TPOriginator = tpo;
                TPOriginator.third_party__r = tpo.third_party__r;                
                TPOriginator.third_party__c = tpo.third_party__c;                
                TPOriginatortRelContact.Other_Originator__c = tpo.name;
            }
        }

    }
}