src/objects/Interaction__c.object
<CustomObject>
    <fields>
        <fullName>Caller_Id_ANI__c</fullName>
        <label>Caller Phone Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Caller_Type__c</fullName>
        <description>This field will have the caller type</description>
        <label>Caller Type</label>
        <picklist>
            <picklistValues>
                <fullName>Benefit Adminstrator/Unlisted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>General Agent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Third Party</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Listed Broker of Record</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Listed General Agent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>President</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vice President</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Director</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chief Executive Officer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chief Operating Officer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chief Financial Officer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Controller</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Assistant Controller</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Member Note</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unlisted Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Owner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UHC Employee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Primary Benefits Administrator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Primary Billing Administrator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Broker</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Claim_Authorization_Referral_Number__c</fullName>
        <label>Claim/Authorization/Referral  Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Id__c</fullName>
        <label>ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Member_Date_of_Birth__c</fullName>
        <label>Member Date of Birth</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Member_Id__c</fullName>
        <label>Member ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NPI__c</fullName>
        <label>NPI</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Question_Type__c</fullName>
        <label>Question Type</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TFN_Toll_Free_Number__c</fullName>
        <label>TFN (Toll Free Number)</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Tax_Id__c</fullName>
        <label>Provider Tax ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Interaction</label>
    <nameField>
        <displayFormat>INT-{0}</displayFormat>
        <label>Interaction ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ACETVCCDUtility.cls
public class ACETVCCDUtility{
    public static Interaction__c populateVCCDInfo(Interaction__c intraction){
        String vccdParams = ApexPages.currentPage().getParameters().get('vccdParams');
        system.debug('vccdParams in VCCD utility '+vccdParams);
        if(vccdParams != null && vccdParams != ''){
            ACETVCCDInteractionInfo vccdInfo = (ACETVCCDInteractionInfo)JSON.deserialize(vccdParams,ACETVCCDInteractionInfo.class);
            system.debug('vccdInfo >>>> '+vccdInfo);
            if(vccdInfo.callerANI != null){
            	intraction.Caller_Id_ANI__c = vccdInfo.callerANI;
            }
            	
            intraction.Question_Type__c = vccdInfo.QuestionType;//will be mapped with question type code using configurator.
            intraction.TFN_Toll_Free_Number__c = vccdInfo.TFN;
            intraction.id__c = vccdInfo.idStr;
            intraction.Caller_Type__c = 'Member';//for demo only. will get change using custom setting
            if(vccdinfo.CallerID != null){
            	intraction.Caller_Id_ANI__c = vccdinfo.CallerID;
            }

            if(vccdinfo.MemberDOB != null && vccdinfo.MemberDOB != '')
                intraction.Member_Date_of_Birth__c = Date.parse(vccdinfo.MemberDOB);//Date.valueof(vccdinfo.MemberDOB);
            intraction.Tax_Id__c = vccdinfo.TaxID;
            intraction.NPI__c = vccdinfo.npi;
            intraction.Member_Id__c = vccdinfo.MemberID;
            intraction.Caller_Type__c = vccdinfo.callerType;
           
            
            if(!String.isEmpty(vccdinfo.ReferralNumber)){
            	 intraction.Claim_Authorization_Referral_Number__c = vccdinfo.ReferralNumber;
            }
            if(!String.isEmpty(vccdinfo.AuthorizationNumber)){
            	 intraction.Claim_Authorization_Referral_Number__c = vccdinfo.AuthorizationNumber;
            }            
            if(!String.isEmpty(vccdinfo.ClaimID)){
            	 intraction.Claim_Authorization_Referral_Number__c = vccdinfo.ClaimID;
            }            
            
            
            
        }
        return intraction;
    }
}